<?php
$companyNames = [
'A.P. Møller - Mærsk',
'Novo Nordisk',
'ISS',
'Arla Foods',
'DONG Energy',
'Carlsberg',
'Vestas Wind Systems',
'Danish Crown',
'Dansk Supermarked',
'DSV',
'DLG',
'Coop Danmark',
'United Shipping & Trading Company',
'Danfoss',
'Lego',
'SAS Group',
'Danish Agro',
'Grundfos',
'TDC',
'Bestseller',
'Danske Commodities',
'Siemens Wind Power',
'NEAS Energy',
'FLSmidth & Co.',
'Dagrofa',
'Statoil Refining Denmark',
'DT Group Holdings',
'VKR Holding',
'Pandora',
'NKT Holding',
'Rockwool International',
'Energi Danmark',
'Falck Holding',
'Rema 1000 Danmark',
'H. Lundbeck',
'Jysk Holding',
'Novozymes',
'Coloplast',
'DFDS',
'Dansk Shell',
'Schouw & Co.',
'Energinet.dk',
'Egmont',
'Hempel Gruppen',
'DSB',
'Dampskibsselskabet Norden',
'Kopenhagen Fur',
'Monjasa Holding',
'William Demant Holding (Oticon)',
'Rambøll Gruppen',
'Solar',
'Semler Gruppen',
'Per Aarsleff',
'Ecco Sko',
'Nets Holding',
'Biomar Group',
'Leo Pharma',
'Circle K Danmark',
'GN Store Nord',
'Also',
'Euro Cater Group',
'Jysk i Tyskland',
'OK',
'PostNord Danmark',
'Icopal',
'House of Prince',
'MSC Scandinavia Holding',
'Scandinavian Tobacco Group',
'Jeld-Wen',
'Aalborg Portland Holding',
'MT Højgaard',
'Chr. Hansen Holding',
'Bygma Gruppen',
'Thornico',
'Royal Unibrew',
'Fleggaard Holding',
'Nomeco',
'Haldor Topsøe',
'Orifarm Group',
'LM Wind Power Holding',
'Cowi',
'Atea',
'J-F. Lemvigh-Müller Holding',
'IBM Danmark',
'XL-Byg',
'Ultranav',
'Elgiganten',
'Hofor Forsyning Holding',
'KMD',
'Blue Water Holding',
'Tican',
'Telenor Danmark Holding',
'Interdan Holding',
'Alfa Laval i Danmark',
'Royal Greenland',
'Telia Company Danmark',
'Danske Spil',
'Nic. Christiansen Holding',
'Aller Holding',
'HMN Naturgas',
'Zerochaos (Nordic)',
'Harald Nyborg',
'Scan Group',
'Q8 Danmark',
'SE',
'SEAS-NVE',
'Thomas Cook Airlines Scandinavia',
'Sanistål',
'NCC Danmark',
'Saint-Gobain Distribution Denmark',
'Cheminova',
'Københavns Lufthavne',
'DR',
'Top-Toy',
'MHI Vestas Offshore Wind',
'Stena Weco',
'AVK Holding',
'IKEA Danmark',
'Abena Holding',
'DuPont Nutrition Biosciences',
'Sund og Bælt Holding',
'Wrist Ship Supply',
'Ejner Hessel Holding',
'Torm',
'Aldi Holding',
'Zebra',
'Uno-X Energi',
'Scandferries',
'Matas',
'DLF Seeds',
'Arkil Holding',
'Siemens',
'Tjellesen Max Jenne',
'Fragtmænd Holding',
'Widex Holding',
'Radiometer Medical',
'Scan Global Logistics koncernen',
'HS Metalservice',
'Copenhagen Metro Team',
'EnergiMidt Holding',
'H&M Hennes & Mauritz',
'JP/Politikens Hus',
'Polar Seafood Greenland',
'Mercedes-Benz Danmark',
'Linak Holding',
'Bladt Industries',
'Nowaco',
'Modern Times Group MTG',
'Sirena Group',
'Hi3G Denmark',
'SOS International',
'Bakkafrost',
'Norpharma',
'Santa Fe Group',
'Magasin',
'Nordic Seafood',
'Ford Motor Company',
'IC Group',
'TV2/Danmark',
'Bang & Olufsen',
'Brdr. A. & O. Johansen',
'Marius Pedersen',
'Unifeeder',
'Norican Global',
'NNIT',
'ALK-Abelló',
'Deloitte',
'EY',
'Nordic Sugar',
'Autohuset Vestergaard Holding',
'Kemp & Lauritzen',
'BHJ',
'Hewlett-Packard',
'Forenede',
'Nordic Aviation Capital',
'DK Company',
'Hørkram Holding',
'Freja Transport & Logistics Holding',
'KNI',
'Jacob Holm & Sønner Holding',
'J. Lauritzen',
'Lenovo Danmark',
'Arrow ECS Denmark',
'Insepa',
'Tech Data Denmark',
'Gasa Group Holding',
'Micro Matic',
'3C Holding (L Easy)',
'NRGi',
'ABB',
'Trefor',
'Verdo',
'Huscompagniet',
'KPC Holding',
'M.J. Eriksson Holding',
'F. Uhrenholt Holding',
'7-Eleven Danmark',
'Arriva Danmark',
'JF Tenura (Jensen Group)',
'Burmeister & Wain Scandinavian Contractor',
'CTR',
'SimCorp',
'Hedeselskabet',
'BPW Finans',
'FF Skagen',
'Synoptik',
'Foss',
'McDonalds Danmark',
'Toyota Danmark',
'FTZ Autodele & Værktøj',
'SB Pork',
'Stibo',
'NDI Holding',
'Givesco',
'Co-Ro Holding',
'JN Data',
'National Oilwell Varco Denmark',
'NLMK DanSteel',
'Satair',
'PwC',
'Bauhaus Danmark',
'Leman Holding',
'Schneider Electric Danmark',
'Viking Life-Saving Equipment',
'Ambu',
'CP Kelco',
'Flügger',
'EG',
'Kuehne + Nagel',
'H.J. Hansen Holding',
'Kangamiut Holding',
'Danpo',
'Atta Holding',
'Øresundsbro Konsortiet',
'Dansk Retursystem',
'Glud & Marstrand',
'Toms Gruppen',
'Vestjyllands Andel',
'C.W. Obel',
'Triplenine Group',
'Jet Time',
'DHL Global Forwarding',
'Nellemann International Holding',
'EET Group',
'Hornsyld Korn-',
'Nordic Transport Group',
'Stena Recycling',
'Babcock & Wilcox Vølund',
'Iddesign',
'Citroen Danmark',
'ALD Automotive',
'Bravida Danmark',
'Takeda Pharma',
'Logstor koncernen',
'NCC Industry',
'Nobia Denmark',
'Gea Process Engineering',
'Carl Erik Larsen Holding',
'Welltec',
'Andelsselskabet af 1. juni 2016',
'SDC',
'Berlingske Media',
'Unomedical',
'Damstahl',
'H+H International',
'Munck Gruppen',
'DFN Olie Holding',
'R. Færch Plast',
'Dako Denmark',
'BP Aviation',
'Accenture',
'Spies',
'Chr. Olesen & Co.',
'Kilroy International',
'Dentsu Aegis Network',
'HCS Transport & Spedition',
'Jysk Fynske Medier',
'Asko',
'Hada Holding',
'Tumlare Corporation',
'Davidsens Tømmerhandel',
'Dan-Foam',
'A. Enggaard Holding',
'Consolidated Holdings',
'Ingram Micro Mobility Denmark',
'M.J. Grønbech & Sønner Holding',
'Haarslev Industries',
'Terma',
'Hess Denmark',
'Kivi-tex',
'Via Biler Gruppen',
'Beumer',
'SAP Danmark',
'AAK Denmark',
'Sønderborg Korn-',
'Philip Morris',
'Unilever Danmark',
'CSC Danmark',
'DHL Express Denmark',
'DCC Energi Danmark',
'Scania Danmark',
'Despec Nordic Holding',
'Kompan',
'Give Stålspær',
'Star Tour',
'Tvilum',
'Clipper Group',
'L Oréal Danmark',
'Harboes Bryggeri',
'Cembrit Group',
'Tomex Danmark',
'Sandoz',
'Energi Fyn',
'Nordex Holding',
'Bayer',
'Statens Serum Institut',
'Holdingselskabet J. Jensen',
'CM Holding',
'Hoffmann',
'Johnson Controls Denmark',
'Cimbria',
'Schenker',
'Danica Ejendomsselskab',
'SP Group',
'NIRAS Gruppen',
'Whiteaway Group',
'Allianceplus Holding',
'Barslund Group',
'Berendsen Textil Service',
'Thrane & Thrane',
'Cargill Nordic',
'SPX Flow Technology',
'BASF',
'Elopak Denmark',
'Good Food Group',
'Knudseje Holding',
'Fujitsu',
'Ikast Betonvarefabrik',
'Polen Invest',
'Opel Danmark',
'KJ Holding',
'Züblin',
'Ferring Pharmaceuticals',
'HKscan Denmark',
'G4S Security Services',
'Fam. Per Bonnichsen Holding',
'Metroselskabet',
'Agro Supply',
'Omnicom Media Group',
'A. Enggaard Kraner',
'Actona Company',
'Kohberg koncernen',
'Boconcept Holding',
'BMW Danmark',
'Zyxel Communications',
'William Cook Europe',
'CRH Concrete',
'Xellia Pharmaceuticals',
'Air Greenland',
'Global Business Travel',
'BEC (Bankernes EDB Central)',
'Jeudan',
'Kurt Skare Holding',
'Sonion',
'kk-group',
'Force Technology',
'Dansac',
'Danæg',
'Fibervisions',
'JBH Gruppen',
'Norisol',
'The TC Group',
'Schur International Holding',
'Fjernvarme Fyn',
'Vattenfall',
'Vindenergi Danmark',
'Bankdata',
'Biogen Denmark Manufacturing',
'Veks',
'Johannes Fog',
'M.M. 26 Holding',
'DS Gruppen',
'Rezidor Hotels Danmark',
'Hans Just Group',
'Georg Jensen',
'Sitecore Corporation',
'Genmab',
'Ib Andresen Industri',
'Dragsbæk',
'Fayard Holding',
'Columbus',
'Compass Group Danmark',
'Dades',
'Alcon Nordic',
'Total Denmark',
'Stema Shipping',
'Paranova Group',
'Sweco Danmark',
'Kvik',
'AudioNord International',
'Martin Professional',
'KMC Kartoffelmelcentralen',
'K. Nissen International',
'Imerco',
'Codan Medical Holding',
'Parken Sport & Entertainment',
'DS Smith Packaging Denmark',
'Geia Food',
'Palsgaard',
'Sport Nordic Holding',
'Smurfit Kappa Danmark',
'Orkla Foods Danmark',
'JKS Group',
'Conaxess Trade Denmark',
'Bjarne Nielsen Holding',
'Volvo Danmark',
'Power',
'Dachser Denmark',
'Brüel & Kjær Sound & Vibration Measurement',
'Fitness World',
'Discovery Networks Denmark',
'Løvbjerg Supermarked',
'Havi Logistics',
'Sapa Precision Tubing Tønder',
'Saint-Gobain Denmark',
'Nordjyske Medier',
'Huawei Technologies Denmark',
'Caverion Danmark',
'Colas Danmark',
'Microsoft Danmark',
'P. Christensen Holding',
'BPI',
'Bavarian Nordic',
'T. Hansen Gruppen',
'Saria Denmark',
'Teknologisk Institut',
'Vega Sea',
'Kyocera Unimerco',
'North Media',
'Starco Europe',
'Carl Christensen Aarhus',
'Gebr. Heinemann Retail',
'Scandic Hotel',
'Pisiffik',
'KDK Holding (Karstensens Skibsværft)',
'Løgismose Meyers',
'Esvagt',
'Arp-Hansen Holding',
'Bonava Danmark',
'UPS Danmark',
'Nagel Danmark',
'Antalis CC&CO',
'BSH Hvidevarer',
'Rynkeby Foods',
'Danske Færger',
'Knauf',
'JHB Holding',
'McKinsey & Company',
'Inwido Denmark',
'Global Castings Holding',
'Danhatch Denmark',
'Yara Danmark Gødning',
'Sondex Holding',
'Egetæpper',
'European Fertilizer',
'General Logistics Systems Denmark',
'RN Holding',
'Reckitt Benckiser Nordic',
'Kvadrat Holding',
'Jørgensen & Utoft',
'Total Produce Nordic',
'Aura Energi',
'Naviair',
'Lantmännen Unibake Denmark',
'Thise Mejeri',
'Kelsen Group',
'Tivoli',
'BDO',
'Uggerhøj Holding',
'Vestforsyning',
'If IT Services',
'CNH Industrial Danmark',
'NGF Nature Energy Holding',
'Vestforbrænding',
'Sapa Extrusion Denmark',
'Roche',
'Group Nordic',
'NovCo Holding II',
'DHI',
'Jan Nygaard',
'Jacobs Douwe Egberts DK',
'Mollerup Mølle',
'SCA Hygiene Products',
'Adecco',
'Scancom International',
'Janssen-Cilag',
'Stenseminde Holding (Desmi)',
'TT-Netværket',
'Andersen Biler',
'KGH Holding',
'Primera Air Scandinavia',
'Astellas Pharma',
'Wind Group',
'Renoldi Invest',
'Trade Point',
'PWT Holding',
'Bravo Tours',
'Højbjerg Maskinfabrik',
'Philips Danmark',
'Hilton Foods Danmark',
'Pedersen & Nielsen Automobilforretning',
'GPV International',
'Color Line Danmark',
'Ocean Prawns',
'Eli Lilly Danmark',
'Tele Greenland',
'Tajco Group',
'Abacus Medicine',
'Gyldendal',
'Lantmännen Schulstad',
'FDM',
'Gasa Nord Grønt',
'Dechra Veterinary Products',
'Nine United',
'MTSL Holding',
'Keolis Danmark',
'Mammen Mejeri',
'Bagger-Sørensen & Co.',
'Jensens Food Group',
'MAN Truck & Bus Danmark',
'Andersen & Martini',
'Dinex',
'Comwell',
'Friis Poulsen',
'Martin Bencher Group',
'Lindab',
'Brenntag Nordic',
'Vald. Birn Holding',
'Weber-Stephen Nordic',
'Thermo-Transit Danmark',
'Dansk Pelsdyr Foder',
'Struers',
'Bluegarden Holding',
'Dan Cake',
'Hansson & Knudsen Holding',
'Gråkjær',
'Boehringer Ingelheim Danmark',
'Royal Arctic Line',
'Multiline',
'Pindstrup Mosebrug',
'Geodis Wilson Denmark',
'Vorup Tømmerhandel og Byggecenter',
'Statens Ejendomssalg',
'Mediabrands Denmark',
'Netcompany Holding',
'DSV Transport',
'Missionpharma',
'Lind Holding',
'Conscia',
'Mondelez Danmark',
'Vink Nordic Holding',
'Baader Poultry',
'Amcor Flexibles Denmark',
'Schlumberger Danmark',
'Wernsing Scandinavia',
'AH Industries Holding',
'Aller Aqua Group',
'Nordisk Wavin',
'Ingleby Farms & Forests',
'3Shape Holding',
'CGI Danmark',
'DKI Holding',
'HansenGroup',
'Eltel Networks',
'Dansk Træemballage Holding',
'Inter Primo',
'Andersen Motors',
'Nilpeter Holding',
'Kalaallit Nunaanni Brugseni',
'B. Nygaard Sørensen',
'Nordic Bulk Carriers',
'Tetra Pak Processing Systems',
'Louis Poulsen',
'F&H',
'Steelseries',
'Jakon',
'OFS Fitel Denmark',
'Hydrema Holding',
'Würth Danmark',
'Dangroup',
'Kverneland Group Kerteminde',
'Avanti WSH',
'Humac',
'Robert Bosch',
'Plenge Holding (nemlig.com)',
'C.C. Contractor',
'H & S Westergaard',
'Wirtgen Denmark',
'Fors Holding',
'Det Danske Klasselotteri',
'Hydratech Industries',
'Herning Shipping',
'Mediq Danmark',
'Albatros Travel',
'MacArtney',
'Bladkompagniet',
'Valmont SM',
'CJ Holding',
'Coor Service Management',
'Atlantic Invest',
'Haas-Meincke',
'Dansk Boligbyg',
'Einar Kornerup',
'Marel',
'Unity IPR',
'Implement Consulting Group',
'Idavang',
'Novasol',
'Lantmännen Cerealia',
'Mascot International',
'E.ON Wind Services',
'Alectia',
'Legoland',
'Mols-Linien',
'FCA Denmark',
'Sennheiser Communications',
'Comm2ig',
'RM Rich. Müller',
'Eurowind Energy',
'Garmin Nordic Denmark',
'Magn',
'Carl Ras',
'C&D Foods Denmark',
'Esbjerg Forsyning Holding',
'Techtronic Industries Nordic',
'Aarhus Vand',
'Lind & Risør',
'Electrolux Home Products Denmark',
'System Frugt Holding',
'Scanenergi Holding',
'Billund Lufthavn',
'Billetkontoret',
'Meldgaard Holding',
'JTI Denmark',
'Kims',
'Stenhøj Holding',
'SFK Leblanc',
'Danish Air Transport Holding',
'G.S.V. Materieludlejning',
'Baker Hughes Denmark',
'Cemb',
'Lactalis Danmark',
'Schades',
'Burmeister & Wain Energy',
'Kara/Noveren',
'E. Sæther Holding',
'7N',
'Prime Ocean',
'Aalborg Varme',
'PFA Ejendomme',
'Fazer Food Services',
'Caljan Rite-Hite',
'NCC Property Development',
'Novartis Healthcare',
'BC Hospitality Group',
'Howden Axial Fans',
'Meneta Holding',
'Miele',
'Samsøe & Samsøe',
'DEIF',
'Holger Christiansen',
'BKI Foods',
'Mobylife Holding',
'Boxer TV',
'Sjælsø Projektudvikling II',
'Glerup',
'Bording',
'Faroe Ship',
'Stryhns',
'Haribo Lakrids',
'Alex Andersen Ølund Holding',
'Gorenje Group Nordic',
'Milestone Systems',
'Scantruck',
'Skagerak Group',
'Shoe-D-Vision',
'Broen',
'Hamlet Protein',
'Krone Fleet Danmark',
'Nordisk Kellogg',
'Esbjerg Havnesilo',
'Bruger - Hjælper Formidlingen',
'Mediacom Danmark',
'Himmerlands Grovvarer',
'Fiskars Denmark',
'Vestfrost',
'Roulunds Braking',
'Dancopter',
'Nordvand',
'Grene Danmark',
'Hejk',
'Container Centralen',
'Toyota Material Handling',
'D.P.P. Holding',
'Evapco Holdings',
'Nordic Tankers Trading',
'Select Service Partner Denmark',
'Weco-Travel International',
'Vinlageret Randers',
'Spæncom',
'Peder Christian Brejnholt Holding',
'Ball',
'Lars Rosbjerg Andersen Holding',
'Iveco Danmark',
'ITW Construction Products',
'Estée Lauder Cosmetics',
'Schmitz Cargobull Danmark',
'Kosan Crisplant Holding',
'Lemminkäinen',
'Frederiksberg Energi',
'Dyrup',
'PNO Holding',
'Abbvie',
'IdealCombi',
'Ericsson Danmark',
'LeasePlan Danmark',
'Volvo Car Denmark',
'Arkitektgruppen',
'Krone Scanbalt',
'Illum',
'Ardagh Glass Holmegaard',
'SAS Institute',
'Steen & Strøm Holding',
'Fritz Hansen',
'SEB Administration',
'SSG',
'Halliburton Denmark',
'N. C. Nielsen',
'Michael Therkildsen Holding',
'Eurodan-Huse',
'El-Salg',
'Lagkagehuset',
'Brøndum Installationer Holding',
'Lyreco Danmark',
'Teknos',
'Aco Nordic Group',
'TNT Danmark',
'Jørgen Kruuse',
'Arrow Denmark',
'Plus Pack',
'Trioplast Nyborg',
'OY Holding',
'GEH Invest (Gram Equipment)',
'Ole Hansen Holding',
'C.A. Larsen Automobiler',
'Thomsen Food Line',
'Juhler Holding',
'Krüger',
'Contiga Tinglev',
'GlobalConnect',
'DLH',
'TCM Group',
'Skov',
'Linderberg Group',
'Silkeborg Forsyning',
'Sport24',
'Union Engineering',
'Beierholm',
'HHM Holding',
'Valcon Business Development',
'Canon Danmark',
'Pfizer',
'Wärtsilä Svanehøj',
'RPC Superfos',
'Skanska',
'Banijay International',
'Auto Akku',
'West Pharmaceutical Services Danmark',
'Atos It Solutions And Services',
'GlaxoSmithKline Consumer Healthcare',
'Pam Holding (Lindberg)',
'Vestergaard Company Holding',
'T-Systems Nordic',
'Gilleleje Transport',
'HV Holding',
'Smyril Line',
'Sun-Air of Scandinavia',
'Skiold',
'5E Holding',
'Neslein Holding (Launis)',
'Emmelev',
'Forsyning Helsingør',
'Fuglsang Holding',
'Hilding Anders Danmark',
'Systematic',
'Studsgaard Holding',
'Atlantic Airways',
'Frederikshavn Forsyning',
'3M',
'Energi Viborg',
'Total Wind Group',
'C. Larsen Holding',
'SK Forsyning',
'Holmris',
'Volvo Entreprenørmaskiner',
'Zacco',
'Illums Bolighus Holding',
'Johs. Møllers Maskiner',
'MEC Denmark',
'Sydvestjydsk Pelsdyrfoder',
'Sole Holding',
'Louis Nielsen',
'Delika Food Group',
'BTX Group',
'Parker Hannifin Danmark',
'Interstil',
'Indeks Retail',
'Securitas',
'B. Bøllingtoft Holding',
'Transcargo Holding',
'Brother Nordic',
'Aleris Hamlet Hospitaler',
'Pon Power',
'Kim Krøjby Holding (Leki Aviation)',
'Telefonverkid',
'Kaufmann',
'Hjort Knudsen',
'Grundtvig Invest',
'Kronospan',
'By & Havn',
'Anders Nielsen & Co',
'Taster Wine',
'Microsoft Development Center Copenhagen',
'Kim Johansen Holding',
'Duferco Danish Steel',
'Tide Bus Danmark',
'Intego',
'Elindco Byggefirma',
'Hardi International',
'Tamaco Holding',
'Nordic Camp Supply',
'Dencon Foods',
'Benteler Aluminium Systems',
'EMR. Murer & Entreprenør',
'Exhausto',
'Aasted',
'Sjællandske Medier',
'Blücher Metal',
'Colgate-Palmolive',
'AGA',
'RGS 90',
'F.B. Holding',
'Navision Group',
'Egil Rasmussen Holding',
'Nestle Danmark',
'Waoo',
'Prodata Consult',
'VJ Investment',
'Adserballe & Knudsen Holding',
'Pressens Fællesindkøbsforening',
'CF Petersen & Søn',
'VPG Holding',
'Tømmergaarden Holding',
'Fodercentralen Limfjorden',
'SEC DataCom',
'GKN Wheels Nagbøl',
'Kunststof-Kemi Skandinavia',
'Alimex Seafood',
'Hillerød Forsyning Holding',
'Hjerting Systeminvest',
'Kjaer Group',
'Prime Cargo',
'Moe',
'Global Wind Service',
'Renonorden',
'Mars Danmark',
'Aarstiderne',
'Østergaard Biler',
'Andritz Feed & Biofuel',
'Akzo Nobel Salt',
'Pon Equipment',
'BC Group',
'Qubiqa Holding',
'CSC Scandihealth',
'Air Liquide Danmark',
'M. Larsen Vognmandsfirma',
'Kimbo Holding',
'Cremo Ingredients',
'Crep',
'Orkla Care',
'RTN Traders',
'All NRG Holding',
'Genua',
'Evergas',
'J. Hvidtved Larsen',
'MSD Danmark',
'DB Cargo Scandinavia',
'Labflex',
'European Energy Holding',
'Pharmacosmos Holding',
'Urtekram International',
'Juan',
'Bilernes Hus',
'Odense Marcipan',
'Nord Energi Net',
'Deas',
'CBP',
'Wittenborg',
'Junckers',
'Nunc',
'Nopa Nordic',
'Adserbi',
'Sæby Fiske-Industri',
'Tibnor',
'SFK Food',
'Povl Bylling',
'Continental Dæk Danmark',
'Phase One',
'Agco Danmark',
'Expedit',
'Aurora Group Danmark',
'Maersk Broker',
'Amager Ressource Center',
'Mobil-Invest DK (Kel-Berg Scandinavia)',
'Orskov Foods',
'BB Electronics',
'Multicut',
'Itelligence',
'P.S.J. Holding (Sand Jensen Automobiler)',
'Fritz Schur Technical Group',
'Catodan Cateringudstyr',
'Roche Diagnostics',
'Svendborg Brakes',
'Universal Robots',
'Pharma Nord',
'Lomax',
'Jupiter Group',
'LMB Danmark',
'Billetten',
'VP Securities',
'Xergi',
'Bankernes Kontantservice',
'KP Group Holding',
'Nobina Danmark',
'Læsø Fiskeindustri',
'Gate Gourmet Denmark',
'Willy Rasmussen Holding',
'Fenrisulven Holding',
'Hans Følsgaard',
'Angel Holding',
'Vandcenter Syd',
'Atria Danmark',
'Joe & The Juice Holding',
'Johs. Rasmussen Svebølle',
'Prysmian Denmark',
'Papyrus',
'DanPilot',
'Noe',
'28. Juni 2012 (SH Group)',
'3S',
'Halberg (Mac Baren Tobacco)',
'Det Norske Veritas Danmark',
'Danespo',
'Michael Henriksen Holding',
'Witt Hvidevarer',
'C.C. Jensen Holding',
'Trelleborg Sealing Solutions Helsingor',
'Metro Service',
'Nilivi Holding',
'Sanofi-Aventis Denmark',
'CSC Airline Solutions Denmark',
'Commercial Real Estate Denmark P/S',
'S.M.S.',
'Fayrefield Foodtec Scandinavia',
'Pro Design',
'Svend Hoyer',
'Interket',
'GF Inveco',
'E 3-Gruppen',
'Konica Minolta',
'Babysam',
'Umove',
'Pressalit',
'Syngenta Nordics',
'BK Medical',
'G.V.L. Entreprise',
'Gasa Odense Frugt - Grønt',
'DK Beton',
'Tresu',
'Oracle Danmark',
'DCH International',
'Barfoed Group',
'Leica Geosystems Technology',
'Carpenter Holdings',
'Loxam',
'Ruko',
'Air Alsie',
'KFI',
'Gram Commercial',
'Soya Concept'
];

$urlEncodeCompanyName = New array();
$noOfCompanies = count(companyNames);
for ($i=0; $i <noOfCompanies ; $i++) { 
	$newCompName = urlencode(companyNames[i]);
	array_push($urlEncodeCompanyName, $newCompName);
}

print_r($urlEncodeCompanyName);
print_r($companyNames);
/*
$googleHostname = "https://www.google.dk";
$googlePath = "/search?";
$googleSearchQueryParam = "q=";


$googleQuery = $googleHostname.$googlePath.$googleSearchQueryParam.$companyNames[1];
->*/